# Generated by Django 3.2.9 on 2021-12-14 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('duration_morning', models.IntegerField(default=0, null=True)),
                ('duration_evening', models.IntegerField(default=0, null=True)),
                ('fare', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_tours',
            },
        ),
        migrations.CreateModel(
            name='TourRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tour.tour')),
            ],
            options={
                'db_table': 'api_tour_ratings',
            },
        ),
    ]
