# Generated by Django 3.2.9 on 2021-12-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_place', '0001_initial'),
        ('api_category', '0001_initial'),
        ('api_tour', '0001_initial'),
        ('api_review', '0002_initial'),
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrating',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.userprofile'),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_category.category'),
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_place.place'),
        ),
        migrations.AddField(
            model_name='tour',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_review.review'),
        ),
    ]
