# Generated by Django 3.2.9 on 2021-12-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_review', '0001_initial'),
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.userprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.userprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_review.vote'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_review.review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.userprofile'),
        ),
    ]
