# Generated by Django 3.2.9 on 2021-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
